"""GuildConfig table, first approach

Revision ID: 1322e2e91ffc
Revises: 
Create Date: 2025-07-08 22:48:38.514182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1322e2e91ffc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_configs',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('welcome_channel_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_index(op.f('ix_guild_configs_guild_id'), 'guild_configs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_guild_configs_welcome_channel_id'), 'guild_configs', ['welcome_channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_configs_welcome_channel_id'), table_name='guild_configs')
    op.drop_index(op.f('ix_guild_configs_guild_id'), table_name='guild_configs')
    op.drop_table('guild_configs')
    # ### end Alembic commands ###
