"""Add language to guild config

Revision ID: 1dbaa588ad9d
Revises: fd4b2deed44d
Create Date: 2025-07-11 21:07:36.076812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dbaa588ad9d'
down_revision: Union[str, Sequence[str], None] = 'fd4b2deed44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('en', 'es', name='supportedlanguage').create(op.get_bind())
    op.add_column('guild_configs', sa.Column('language', postgresql.ENUM('en', 'es', name='supportedlanguage', create_type=False), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_configs', 'language')
    sa.Enum('en', 'es', name='supportedlanguage').drop(op.get_bind())
    # ### end Alembic commands ###
