"""Remove index from pk in GuildConfig

Revision ID: 239e9d87d22d
Revises: 1322e2e91ffc
Create Date: 2025-07-08 22:49:44.577481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239e9d87d22d'
down_revision: Union[str, Sequence[str], None] = '1322e2e91ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_configs_guild_id'), table_name='guild_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_guild_configs_guild_id'), 'guild_configs', ['guild_id'], unique=False)
    # ### end Alembic commands ###
