"""Add welcome enabled option

Revision ID: 28d982570d05
Revises: 1e3854a0fe43
Create Date: 2025-07-09 20:19:43.715964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d982570d05'
down_revision: Union[str, Sequence[str], None] = '1e3854a0fe43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_configs', sa.Column('welcome_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_configs', 'welcome_enabled')
    # ### end Alembic commands ###
