"""Add polls message and max limit to messages

Revision ID: 709ecbf97ae4
Revises: e536b4bf797a
Create Date: 2025-07-09 23:09:12.835063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '709ecbf97ae4'
down_revision: Union[str, Sequence[str], None] = 'e536b4bf797a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_configs', sa.Column('polls_message', sqlmodel.sql.sqltypes.AutoString(length=2000), server_default='A new poll has been created! @everyone', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_configs', 'polls_message')
    # ### end Alembic commands ###
