"""Add welcome message option

Revision ID: 93625a54aa8c
Revises: 28d982570d05
Create Date: 2025-07-09 20:36:11.428114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93625a54aa8c'
down_revision: Union[str, Sequence[str], None] = '28d982570d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_configs', sa.Column('welcome_message', sqlmodel.sql.sqltypes.AutoString(), server_default='Welcome %MEMBER% to the server! Enjoy your stay! If you have any questions, feel free to ask.', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_configs', 'welcome_message')
    # ### end Alembic commands ###
