"""Add polls channel id setting

Revision ID: e536b4bf797a
Revises: 93625a54aa8c
Create Date: 2025-07-09 22:29:41.181290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e536b4bf797a'
down_revision: Union[str, Sequence[str], None] = '93625a54aa8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_configs', sa.Column('polls_channel_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_guild_configs_polls_channel_id'), 'guild_configs', ['polls_channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_configs_polls_channel_id'), table_name='guild_configs')
    op.drop_column('guild_configs', 'polls_channel_id')
    # ### end Alembic commands ###
