"""Create UserProfile model

Revision ID: fd4b2deed44d
Revises: cf66be0b63cd
Create Date: 2025-07-10 21:54:29.471532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd4b2deed44d'
down_revision: Union[str, Sequence[str], None] = 'cf66be0b63cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.guild_id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
